In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs

/Users/vipulgarg/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [1]:
def mySoftMax(z):
    ez = np.exp(z)
    sm = ez/np.sum(ez)
    return (sm)

In [3]:
# Multi-class classification problem

# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [4]:
# 1st method to make model

model1 = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4, activation='softmax')
    ]
)
model1.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model1.fit(
    X_train, y_train, epochs=10
)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - loss: 1.0817 
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 0.3959
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 339us/step - loss: 0.1851
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - loss: 0.1082
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - loss: 0.0789
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - loss: 0.0699
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 0.0534
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - loss: 0.0497
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - loss: 0.0492
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - loss: 0.0436


In [5]:
p_nonPrefereed = model1.predict(X_train)
print(p_nonPrefereed[:2])
print("largest value", np.max(p_nonPrefereed), "smallest value", np.min(p_nonPrefereed))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step
[[6.2477244e-03 5.9521901e-03 9.7747868e-01 1.0321485e-02]
 [9.9237925e-01 7.5474917e-03 3.8222792e-05 3.5124947e-05]]
largest value 0.99999857 smallest value 1.0626687e-08


In [7]:
# More numerically accurate model

model2 = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4, activation='linear'),
    ]
)

model2.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
               optimizer=tf.keras.optimizers.Adam(0.001)
)

model2.fit(X_train, y_train, epochs=10)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - loss: 1.5066 
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - loss: 0.5878
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 334us/step - loss: 0.2610
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 338us/step - loss: 0.1438
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - loss: 0.0915
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - loss: 0.0767
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - loss: 0.0634
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 329us/step - loss: 0.0521
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - loss: 0.0443
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - loss: 0.0443


In [9]:
p_preferred = model2.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step
two example output vectors:
 [[-0.9776633  -1.0525728   5.6543818   2.1894321 ]
 [ 7.0444407  -0.16915305  0.24221791  0.85761654]]
largest value 17.430668 smallest value -7.346873


In [10]:
sm_preferred=tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[1.2743742e-03 1.1823992e-03 9.6729165e-01 3.0251643e-02]
 [9.9611104e-01 7.3364121e-04 1.1069805e-03 2.0483497e-03]]
largest value 0.99999905 smallest value 6.3184435e-10


In [11]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-0.9776633 -1.0525728  5.6543818  2.1894321], category: 2
[ 7.0444407  -0.16915305  0.24221791  0.85761654], category: 0
[ 4.8162746   0.48858207 -0.01277561  0.5152905 ], category: 0
[-2.3279788   3.8593996  -1.4687927  -0.36384702], category: 1
[ 3.911297  -1.9000175  8.560036   1.7560073], category: 2
